version: '3'

services:
  nats-server:
    container_name: nats-server
    image: nats:latest
    ports:
      - 4222:4222
    networks:
      - nats-redis-mongo-network

  redis-server:
    container_name: redis-server
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - nats-redis-mongo-network

  mongo-server:
    container_name: mongo-server
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ica
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - nats-redis-mongo-network

  # account-service:
  #   container_name: account-service
  #   build:
  #     context: ./account-service
  #   environment:
  #     - MONGO_DSN=mongodb://ica:password1234@mongodb:27017
  #     - MONGO_MAX_IDLE_TIME=10s
  #     - MONGO_MAX_IDLE_CONN=10
  #     - AUTH_SECRETKEY=5dge967dus^8hs6dA$SU@JE
  #     - LOG_LEVEL=debug
  #     - SERVER_BASE=
  #     - SERVER_PORT=50051
  #   networks:
  #     - nats-redis-mongo-network
  #   depends_on:
  #     - nats-server
  #     - redis-server
  #     - mongo-server

  # api-gateway:
  #   container_name: api-gateway
  #   build:
  #     context: ./api-gateway
  #   environment:
  #     - AUTH_SECRETKEY=5dge967dus^8hs6dA$SU@JE
  #     - LOG_LEVEL=debug
  #     - SERVER_BASE=
  #     - SERVER_PORT=8080
  #     - GRPC_SERVER_BASE=localhost
  #     - GRPC_SERVER_PORT=50051
  #   networks:
  #     - nats-redis-mongo-network
  #   depends_on:
  #     - account-service

networks:
  nats-redis-mongo-network:
    driver: bridge
